packages:
  - packages/*
autoInstallPeers: true
configDependencies:
  "@effected/pnpm-plugin-effect": 0.13.0
  "@savvy-web/pnpm-plugin-silk": 0.46.0
minimumReleaseAgeExclude:
  - "@rolldown/binding-openharmony-arm64@1.2.8"
